# Generated by Django 4.1 on 2023-02-15 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_approved_comment_comment_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
